version: 3

groups:
  general:
    conditions:
    - "files.exclude('src/abstraction/eq1Producteur1/*')"
    - "files.exclude('src/abstraction/eq2Producteur2/*')"
    - "files.exclude('src/abstraction/eq3Transformateur1/*')"
    - "files.exclude('src/abstraction/eq4Transformateur2/*')"
    - "files.exclude('src/abstraction/eq5Transformateur3/*')"
    - "files.exclude('src/abstraction/eq6Distributeur1/*')"
    - "files.exclude('src/abstraction/eq7Distributeur2/*')"
    - "files.exclude('src/abstraction/eq8Romu/*')"
    reviewers:
      users:
      - massimotisi
    reviews:
      required: 1
      author_value: 1

  eq1:
    conditions:
    - "files.include('src/abstraction/eq1Producteur1/*')"
    reviews:
      required: 1
      author_value: 1
    reviewers:
      teams: 
      - eq1Producteur1

  eq2:
    conditions:
    - "files.include('src/abstraction/eq2Producteur2/*')"
    reviews:
      required: 1
      author_value: 1
    reviewers:
      teams: 
      - eq2Producteur2

  eq3:
    conditions:
    - "files.include('src/abstraction/eq3Transformateur1/*')"
    reviews:
      required: 1
      author_value: 1
    reviewers:
      teams: 
      - eq3Transformateur1

  eq4:
    conditions:
    - "files.include('src/abstraction/eq4Transformateur2/*')"
    reviews:
      required: 1
      author_value: 1
    reviewers:
      teams: 
      - eq4Transformateur2

  eq5:
    conditions:
    - "files.include('src/abstraction/eq5Transformateur3/*')"
    reviews:
      required: 1
      author_value: 1
    reviewers:
      teams: 
      - eq5Transformateur3

  eq6:
    conditions:
    - "files.include('src/abstraction/eq6Distributeur1/*')"
    reviews:
      required: 1
      author_value: 1
    reviewers:    
      teams: 
      - eq6Distributeur1

  eq6:
    conditions:
    - "files.include('src/abstraction/eq7Distributeur2/*')"
    reviews:
      required: 1
      author_value: 1
    reviewers:    
      teams: 
      - eq7Distributeur2

  eq6:
    conditions:
    - "files.include('src/abstraction/eq8Romu/*')"
    reviews:
      required: 1
      author_value: 1
    reviewers:    
      teams: 
      - eq8Romu